apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfm-g005-vol01
  labels:
    type: local
spec:
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/D/Workspace-TFM/TFM/es.rcs.tfm/es.rcs.tfm.corpus/persistence/005G_01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfm-g005-vol02
  labels:
    type: local
spec:
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/D/Workspace-TFM/TFM/es.rcs.tfm/es.rcs.tfm.corpus/persistence/005G_02"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfm-g005-vol03
  labels:
    type: local
spec:
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/D/Workspace-TFM/TFM/es.rcs.tfm/es.rcs.tfm.corpus/persistence/005G_03"
