apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-solr
  labels:
    app: tfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm
      tier: solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tfm
        tier: solr
    spec:
      containers:
      - image: dukegris/tfm_solr:1.0.2
        name: solr
#        resources:
#          limits:
#            cpu: 512m
#            memory: 512Mi
#          requests:
#            cpu: 512m
#            memory: 128Mi
        ports:
        - containerPort: 8983
          name: solr
        volumeMounts:
        - name: solr-metadata
          mountPath: /var/lib/solr
        - name: solr-data
          mountPath: /var/lib/tfm
        - name: solr-log
          mountPath: /var/log/solr
      volumes:
      - name: solr-metadata
        persistentVolumeClaim:
          claimName: solr-metadata-claim
      - name: solr-data
        persistentVolumeClaim:
          claimName: solr-data-claim
      - name: solr-log
        persistentVolumeClaim:
          claimName: solr-log-claim
