apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-spark-master
  labels:
    app: tfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm
      tier: spark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tfm
        tier: spark
    spec:
      containers:
      - name: spark-master
        image: dukegris/tfm_spark:1.0.2
        command: ["/usr/local/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
#        resources:
#          limits:
#            cpu: 512m
#            memory: 512Mi
#          requests:
#            cpu: 512m
#            memory: 128Mi
        ports:
        - containerPort: 8080
          name: spark-port
        - containerPort: 7070
          name: spark-listener
        volumeMounts:
        - name: spark-master-log
          mountPath: /var/log/spark-master
      volumes:
      - name: spark-master-log
        persistentVolumeClaim:
          claimName: spark-master-log-claim
