apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-postgresql
  labels:
    app: tfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfm
      tier: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tfm
        tier: postgresql
    spec:
      containers:
      - name: postgresql
        image: dukegris/tfm_postgresql:1.0.2
#        resources:
#          limits:
#            cpu: 512m
#            memory: 512Mi
#          requests:
#            cpu: 512m
#            memory: 128Mi
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: pg-metadata
          mountPath: /var/lib/postgresql
        - name: pg-data
          mountPath: /var/lib/tfm
        - name: pg-log
          mountPath: /var/log/postgresql
      volumes:
      - name: pg-metadata
        persistentVolumeClaim:
          claimName: pg-metadata-claim
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data-claim
      - name: pg-log
        persistentVolumeClaim:
          claimName: pg-log-claim
