apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-spark-worker
  labels:
    app: tfm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tfm
      tier: spark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tfm
        tier: spark
    spec:
      containers:
      - name: spark-worker
        image: dukegris/tfm_spark:1.0.2
        command: ["/usr/local/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
#        resources:
#          limits:
#            cpu: 512m
#            memory: 512Mi
#          requests:
#            cpu: 512m
#            memory: 128Mi
        ports:
        - containerPort: 8080
          name: spark-port
        - containerPort: 7070
          name: spark-listener
        volumeMounts:
        - name: spark-worker-log
          mountPath: /var/log/spark-worker
      volumes:
      - name: spark-worker-log
        persistentVolumeClaim:
          claimName: spark-worker-log-claim
