apiVersion: v1
kind: Service
metadata:
  name: tfm-solr
  labels:
    app: tfm
spec:
  selector:
    app: tfm
    tier: solr
  ports:
    - name: solr-port
      protocol: TCP
      port: 8983
      targetPort: 8983
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: tfm-postgresql
  labels:
    app: tfm
spec:
  selector:
    app: tfm
    tier: postgresql
  ports:
    - name: postgresql-listener
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: tfm-spark-master
  labels:
    app: tfm
spec:
  selector:
    app: tfm
    tier: spark
  ports:
    - name: spark-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: spark-listener
      protocol: TCP
      port: 7070
      targetPort: 7070
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: tfm-spark-worker
  labels:
    app: tfm
spec:
  selector:
    app: tfm
    tier: spark
  ports:
    - name: spark-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: spark-listener
      protocol: TCP
      port: 7070
      targetPort: 7070
  clusterIP: None