version: '3.8'

services:
  postgresql:
    image: dukegris/tfm_postgresql:1.0.2
    networks: 
      backend:
    volumes:
      - type: volume
        source: pg-metadata
        target: /var/lib/postgresql
        volume:
          nocopy: false
      - type: volume
        source: pg-data
        target: /var/lib/tfm
        volume:
          nocopy: false
      - type: volume
        source: pg-logs
        target: /var/log/postgresql
        volume:
          nocopy: false
    ports:
      - 5432:5432
  solr:
    image: dukegris/tfm_solr:1.0.2
    networks: 
      backend:
    volumes:
      - type: volume
        source: solr-metadata
        target: /var/lib/solr
        volume:
          nocopy: false
      - type: volume
        source: solr-data
        target: /var/lib/tfm
        volume:
          nocopy: false
      - type: volume
        source: solr-logs
        target: /var/log/solr
        volume:
          nocopy: false
    ports:
      - 8983:8983
  spark-master:
    image: dukegris/tfm_spark:1.0.2
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master
    hostname: master
    networks: 
      spark:
    volumes:
      - type: volume
        source: spark-master-logs
        target: /var/log/spark
        volume:
          nocopy: false
    ports:
      - 8080:8080
      - 7077:7077
  spark-worker:
    image: dukegris/tfm_spark:1.0.2
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks: 
      spark:
    depends_on:
      - spark-master
    volumes:
      - type: volume
        source: spark-worker-logs
        target: /var/log/spark
        volume:
          nocopy: false
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - 8081-8089:8080

networks:
  backend:
  spark:
            
volumes:
  pg-metadata:
    external: false
    name: pg-metadata
  pg-data:
    external: false
    name: pg-data
  pg-logs:
    external: false
    name: pg-logs
  solr-metadata:
    external: false
    name: solr-metadata
  solr-data:
    external: false
    name: solr-data
  solr-logs:
    external: false
    name: solr-logs
  spark-master-logs:
    external: false
    name: spark-master-logs
  spark-worker-logs:
    external: false
    name: spark-worker-logs
