apiVersion: v1
kind: Service
metadata:
  name: tfm-postgresql
  labels:
    app: tfm
spec:
  selector:
    app: tfm
    tier: postgresql
  ports:
    - name: postgresql-listener
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-metadata-claim
  labels:
    app: tfm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-claim
  labels:
    app: tfm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-log-claim
  labels:
    app: tfm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Deployment
metadata:
  name: tfm-postgresql
  labels:
    app: tfm
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tfm
      tier: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tfm
        tier: postgresql
    spec:
      containers:
      - image: dukegris/tfm_postgresql:1.0.1/
        name: postgresql
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: pg-metadata
          mountPath: /var/lib/postgresql
        - name: pg-data
          mountPath: /var/lib/tfm
        - name: pg-log
          mountPath: /var/log/postgresql
      volumes:
      - name: pg-metadata
        persistentVolumeClaim:
          claimName: pg-metadata-claim
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data-claim
      - name: pg-log
        persistentVolumeClaim:
          claimName: pg-log-claim
      