apiVersion: v1
kind: Service
metadata:
  name: tfm-spark-master
  labels:
    app: tfm
spec:
  selector:
    app: tfm
    tier: spark
  ports:
    - name: spark-master-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: spark-master-listener
      protocol: TCP
      port: 7070
      targetPort: 7070
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-master-log-claim
  labels:
    app: tfm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Deployment
metadata:
  name: tfm-spark-master
  labels:
    app: tfm
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tfm
      tier: spark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tfm
        tier: spark
    spec:
      containers:
      - name: spark-master
        image: dukegris/tfm_spark:1.0.1/
        command: ["/usr/local/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.worker.Worker", "spark://master:7077"]
        ports:
        - containerPort: 8080
          name: spark-master-port
        - containerPort: 7070
          name: spark-master-listener
        volumeMounts:
        - name: spark-master-log
          mountPath: /var/log/spark-master
      volumes:
      - name: spark-master-log
        persistentVolumeClaim:
          claimName: spark-master-log-claim
      
      