apiVersion: v1
kind: Service
metadata:
  name: tfm-spark-worker
  labels:
    app: tfm
spec:
  selector:
    app: tfm
    tier: spark
  ports:
    - name: spark-worker-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: spark-worker-listener
      protocol: TCP
      port: 7070
      targetPort: 7070
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-worker-log-claim
  labels:
    app: tfm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Deployment
metadata:
  name: tfm-spark-worker
  labels:
    app: tfm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tfm
      tier: spark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tfm
        tier: spark
    spec:
      containers:
      - name: spark-worker
        image: dukegris/tfm_spark:1.0.1/
        command: ["/usr/local/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        ports:
        - containerPort: 8080
          name: spark-worker-port
        - containerPort: 7070
          name: spark-worker-listener
        volumeMounts:
        - name: spark-worker-log
          mountPath: /var/log/spark-worker
      volumes:
      - name: spark-worker-log
        persistentVolumeClaim:
          claimName: spark-worker-log-claim
 # https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/     
      